server:
  port: 5003

spring:
  application:
    name: order-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:"
  datasource:
    url: "jdbc:postgresql://localhost:5432/mydb"
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.igdevx.spring_boot_account_microservice: INFO

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
